FROM python:3.12-slim

WORKDIR /app

RUN pip install --upgrade pip && pip install poetry

RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock* ./

RUN poetry install --no-root --no-interaction --no-ansi

RUN apt-get update && apt-get install -y wait-for-it

COPY . .

CMD wait-for-it db:5432 -- python main.py
